import { existsSync, readFileSync } from "fs";
import { join } from "path";

export interface TaskSummary {
  id: number;
  /** Plain-language title generated by Claude. */
  title: string;
  /** SEO impact rationale generated by Claude. */
  whyItMatters: string;
  /** updated_at the summary was generated against — used for cache invalidation. */
  updatedAt: string;
}

export type TaskSummaryCache = Record<string, TaskSummary>; // keyed by todo id

function cachePath(projectId: string): string {
  return join(
    process.cwd(),
    "app",
    "data",
    "clients",
    `${projectId}-task-summaries.json`
  );
}

export function loadTaskSummaries(projectId: string): TaskSummaryCache {
  const p = cachePath(projectId);
  if (!existsSync(p)) return {};
  try {
    return JSON.parse(readFileSync(p, "utf-8")) as TaskSummaryCache;
  } catch {
    return {};
  }
}

export function getTaskSummariesPath(projectId: string): string {
  return cachePath(projectId);
}
